### ISSUE TITLE
Usage filenames are switched in Readme

### ISSUE THREAD

**Issue by SilentRhetoric** [algorandfoundation/algokit-avm-vscode-debugger#17]
Near the top of the Usage section in the readme, the filenames corresponding to the source maps and simulate traces are switched.  

TEAL Source Maps. A ***.trace.avm.json** file that maps the compiled TEAL source maps to the original source code. See an example [here](https://github.com/algorandfoundation/algokit-avm-vscode-debugger/blob/HEAD/examples/multiRootWorkspace/slot-machine/.algokit/sources/sources.avm.json).
Simulate Traces. A **sources.avm.json** file that contains the traces obtained from algod's [simulate endpoint](https://developer.algorand.org/docs/get-details/dapps/smart-contracts/debugging/?from_query=simulate#simulate). This serves as an entry point for the debugger. See an example [here](https://github.com/algorandfoundation/algokit-avm-vscode-debugger/blob/HEAD/examples/multiRootWorkspace/slot-machine/debug_traces/simulate-response.trace.avm.json).

**Comment by neilcampbell** [comment]
Thanks @SilentRhetoric! I'll get that fixed now.
